### ISSUE TITLE
Containerize and write CWL for GATK BaseQualityScoreRecalibrator

### ISSUE THREAD

**Issue by rhshah** [mskcc/cwl-commandlinetools#14]
Tool: GATK BaseQualityScoreRecalibrator
Location: https://software.broadinstitute.org/gatk/download/auth?package=GATK-archive&version=3.3-0-g37228af 
Version: 3.3.0

- [ ]  Container
- [ ]  CWL
- [ ]  Run Test

**Comment by shalabhsuman** [comment]
I can take assignment for this issue

**Comment by rhshah** [comment]
@shalabhsuman lets do the assignment on planning meeting

**Comment by shalabhsuman** [comment]
Will change from GATK3 to GATK4 for this CmdLine tool. Will close this and move this to #30
