### ISSUE TITLE
Containerize and write CWL for GATK3 PrintReads

### ISSUE THREAD

**Issue by rhshah** [mskcc/cwl-commandlinetools#15]
Tool: GATK3 PrintReads
Location: https://software.broadinstitute.org/gatk/download/auth?package=GATK-archive&version=3.3-0-g37228af 
Version: 3.3.0

- [ ]  Container
- [ ]  CWL
- [ ]  Run Test

**Comment by rhshah** [comment]
Try GATK 4

**Comment by allanbolipata** [comment]
If you need it, this is the Dockerfile we use with Conpair which contains GATK 3.8: https://github.com/mskcc/vaporware/blob/master/containers/conpair/Dockerfile

I will add the older version with 3.3.0 anyway so you can have it ready, but GATK 4 is easily available in https://hub.docker.com/r/broadinstitute/gatk/tags?page=1.

**Comment by allanbolipata** [comment]
I have made the container for 3.3.0, located here https://hub.docker.com/r/mskcc/gatk

**Comment by shalabhsuman** [comment]
I am assuming its _safe_ to use the `GATK4 image` directly from **GATK official Docker-Hub** repo rather than building our own GATK image using a dockerfile. Correct?

**Comment by shalabhsuman** [comment]
The module for BQSR has been renamed to `ApplyBQSR` in GATK4 and all the parameters have been renamed as well.

**Comment by rhshah** [comment]
I think we should discuss these in the planning meeting before we change anything

**Comment by shalabhsuman** [comment]
continuing with GATK4..Moving this to #32
