### ISSUE TITLE
Containerize and write CWL for GATK 4 BaseQualityScoreRecalibrator

### ISSUE THREAD

**Issue by rhshah** [mskcc/cwl-commandlinetools#30]
Tool: GATK BaseQualityScoreRecalibrator
Location: https://software.broadinstitute.org/gatk/documentation/tooldocs/current/org_broadinstitute_hellbender_tools_walkers_bqsr_BaseRecalibrator.php
GATK Version: [4.1.2](https://github.com/broadinstitute/gatk/releases/tag/4.1.2.0)

- [x]  Container
- [x]  CWL
- [x]  Run Test

**Comment by shalabhsuman** [comment]
Having error while utilizing the `--java-options "-Xmx4G"` with an error `Could not find or load main class "-Xmx4G"`.

**Comment by shalabhsuman** [comment]
`$(inputs.input.basename.replace('.bam', '')).recal.table` along with `-output` prefix in the Arguments inside CWL gives a warning. @ionox0 

- [ ] Resolved
