### ISSUE TITLE
Marianas Collapsing Second Pass CWL

### ISSUE THREAD

**Issue by rhshah** [mskcc/cwl-commandlinetools#36]
`org.mskcc.marianas.umi.duplex.DuplexUMIBamToCollapsedFastqSecondPass standard-bam-file pileup-file minMappingQuality minBaseQuality mismatches wobble minConsensusPercent reference-fasta-file first-pass.mate-position-sorted.txt`

This will produce `collapsed_R1_.fastq` and `collapsed_R2_.fastq` files along with some `QC files.`

**Comment by ionox0** [comment]
we can probably close this now 💯
