### ISSUE TITLE
Collapsing FirstPass CWL

### ISSUE THREAD

**Issue by rhshah** [mskcc/cwl-commandlinetools#39]
`java -server -Xms8g -Xmx8g -cp Marianas.jar org.mskcc.marianas.umi.duplex.DuplexUMIBamToCollapsedFastqFirstPass bam-file pileup-file minMappingQuality minBaseQuality UMIMismatches UMIWobble minConsensusPercent reference-fasta-file`

**Comment by ionox0** [comment]
we can probably close this now that collapsing cwls are merged
