### ISSUE TITLE
bedtools genomecov

### ISSUE THREAD

**Issue by rhshah** [mskcc/cwl-commandlinetools#41]
version: 2.28

location: https://github.com/arq5x/bedtools2/releases/download/v2.28.0/bedtools

- [x] CWL
- [x] Container
- [x] Test

`bedtools genomecov -bg -ibam  /path/to/bam > out.bedgraph`

You can use these as the starting points:
https://github.com/common-workflow-language/workflows/blob/master/tools/bedtools-genomecov.cwl

**Comment by shalabhsuman** [comment]
#43
