### ISSUE TITLE
bedtools merge

### ISSUE THREAD

**Issue by rhshah** [mskcc/cwl-commandlinetools#42]
version: 2.28

location: https://github.com/arq5x/bedtools2/releases/download/v2.28.0/bedtools

- [x] CWL
- [x] Container
- [x] Test

`bedtools merge -i out.bedgraph -d 400 > out.bed `

**Comment by shalabhsuman** [comment]
I am going to give **Distance between features** (`-d`) as `300` default and at the same time, provide user the option of entering any other value. Let me know if that default needs to be modified

**Comment by shalabhsuman** [comment]
#44

**Comment by rhshah** [comment]
I think we don't need to provide any default. I just thought of giving `400` as if the features are that far apart they get merged as abra2 operated on the window size of `400`. But we can run it without any `-d` option.
